### ISSUE TITLE
doesn't work windows 

### ISSUE THREAD

**Issue by auroracoin** [forknote/configs#16]
doesn't work windows how do i get seed to latest version ? thx :)
dashcoin v2.0.1.1221

2017-Oct-16 14:29:29.915016 INFO    [45.76.34.101:44396 INC] Sync data returned
unknown top block: 677913 -> 817626 [139713 blocks (194 days) behind]
2017-Oct-16 14:29:29.915016 INFO    SYNCHRONIZATION started
2017-Oct-16 14:30:20.476060 INFO    [173.179.248.79:45199 INC] Sync data returne
d unknown top block: 677914 -> 854661 [176747 blocks (245 days) behind]
2017-Oct-16 14:30:20.476060 INFO    SYNCHRONIZATION started

[wallet D9ewFd]: 2017-Oct-16 14:29:29.925023 ERROR   [BlockchainSynchronizer] Fa
iled to query outdated pool transaction: NodeErrorCategory:3, Network error

2017-Oct-16 16:49:49.756496 INFO    [176.31.124.129:29080 OUT] Sync data returne
d unknown top block: 677945 -> 817680 [139735 blocks (194 days) behind]
2017-Oct-16 16:49:49.756496 INFO    SYNCHRONIZATION started
2017-Oct-16 16:49:50.622051 INFO    [108.61.188.93:7610 OUT] Sync data returned
unknown top block: 677945 -> 817680 [139735 blocks (194 days) behind]
2017-Oct-16 16:49:50.622051 INFO    SYNCHRONIZATION started
2017-Oct-16 16:55:59.101433 INFO    [94.130.11.10:59539 INC] Sync data returned
unknown top block: 677952 -> 817680 [139728 blocks (194 days) behind]
2017-Oct-16 16:55:59.101433 INFO    SYNCHRONIZATION started
2017-Oct-16 16:57:49.912767 INFO    [184.164.129.202:63186 INC] Sync data return
ed unknown top block: 677953 -> 817680 [139727 blocks (194 days) behind]
2017-Oct-16 16:57:49.912767 INFO    SYNCHRONIZATION started
2017-Oct-16 16:59:03.068917 INFO    [176.9.47.243:33408 INC] Sync data returned
unknown top block: 677954 -> 854739 [176785 blocks (245 days) behind]

-----------------------------------------------------
conf file makes things worst  dashcoin
rpcuser=user
rpcpassword=password
rpcallowip=localhost
rpcconnect=127.0.0.1
rpcport=29081
port=29080
genproclimit=1
server=1
listen=1
seednode=108.61.188.93:7610
seednode=128.199.146.243:29080
seednode=195.154.181.121:7280
seednode=93.77.229.33:29080
seednode=144.76.59.211:29080
seednode=176.9.147.178:7280
seednode=176.9.47.243:7280
seednode=84.200.76.33:29080
seednode=98.115.76.178:29080
seednode=195.154.181.121:7280

**Comment by typoworx-de** [comment]
same problem here on linux. any help?

**Comment by pmitchev** [comment]
Dashcoin was maliciously forked. You will see this WARNING until effective node ban is implemented. This is huge issue for all bytecoin clones, because I am able to basically cripple all Bytecoin clones with a malicious fork.
The only effect on functionality is slower syncing, which is not small issue at all
