### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by QuinnMallorry** [forknote/configs#21]
Are there suggested intervals at which it makes more sense to add a checkpoint than others? For example, every thousand blocks? Every thousand days? Every release?

Question is directed at @pmitchev, but I'll accept a response from anyone with a suggestion.

**Comment by pmitchev** [comment]
Add checkpoint on every upgrade or so. We should automate this process.

**Comment by QuinnMallorry** [comment]
Thank you for the response, this would make a good `extension/export_checkpoints.json` to allow someone to add it in from output, manually.

**Comment by monotek** [comment]
Where can i find documetnation about checkpoints?
Its not clear to mew what it is / what it does and if i need it or not?

**Comment by oliviersinnaeve** [comment]
Just add a reload command that reads the config file again ?

**Comment by pmitchev** [comment]
@oliviersinnaeve  KISS (keep it simple stupid). Just restarting the daemon is doing the same thing and will avoid adding more code, which have to be maintained
